{
 "title": "Dashboard Manantial",
 "refresh": "5s",
 "panels": [
  {
   "title": "🚀 Estado general de los servicios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Estado de Servicios",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{type=\"backend\"}",
     "legendFormat": "🔧 Backend  {{job}}"
    },
    {
     "expr": "up{type=\"monitoring\"}",
     "legendFormat": "📊 Metricas {{job}}"
    }
   ]
  },
  { "title": "🔧 Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Tasa de Request (Req/Sec)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"customer-service\"}[1m])",
     "legendFormat": "{{job}} - {{uri}} {{status}}"
    }
   ]
  },
  { "title": "📊 Infraestructura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Actual (%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage{type=\"backend\"} * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Consumo De Memoria Heap",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{job}} ({{id}})"
    }
   ]
  },
  {
   "title": "Memoria Heap Usada (%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (jvm_memory_used_bytes{area=\"heap\"} / ignoring(instance) jvm_memory_max_bytes{area=\"heap\"} > 0)",
     "legendFormat": "{{job}} ({{id}})"
    }
   ]
  },
  { "title": "📄 Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Logs de Customer Service [INFO]",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=\"customer-service\"} |= \"INFO\""
    }
   ]
  },
  {
   "title": "Logs de Customer Service [WARN]",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=\"customer-service\"} |= \"WARN\""
    }
   ]
  },
  {
   "title": "Logs de Customer Service [ERROR]",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=\"customer-service\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "Logs de Consumer Service [INFO]",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=\"consumer-service\"} |= \"INFO\""
    }
   ]
  },
  {
   "title": "Logs de Consumer Service [WARN]",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=\"consumer-service\"} |= \"WARN\""
    }
   ]
  },
  {
   "title": "Logs de Consumer Service [ERROR]",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=\"consumer-service\"} |= \"ERROR\""
    }
   ]
  }
 ]
}