apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-local
spec:
  volumeName: redis-pv-local
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis7-deployment
  labels:
    app: redis-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-local
  template:
    metadata:
      labels:
        app: redis-local
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
        - name: fix-permissions
          image: busybox
          command: [ "sh", "-c", "chown -R 10001:10001 /data" ]
          volumeMounts:
            - name: redis-local
              mountPath: /data
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      containers:
        - image: redis:7.2
          name: redis7
          imagePullPolicy: Always
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-local
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5

            # 💡 Recursos recomendados
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: redis-local
          persistentVolumeClaim:
            claimName: redis-pvc-local

---
apiVersion: v1
kind: Service
metadata:
  name: redis7-service-local
spec:
  type: ClusterIP
  selector:
    app: redis-local
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379





