apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets-local
type: Opaque
data:
  keycloak_client_id: c3ByaW5nLWdhdGV3YXktY2xpZW50
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets-local
type: Opaque
data:
  mongo_user: YWRtaW4=
  mongo_password: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets-local
type: Opaque
data:
  redis_password: YWRtaW4=
