apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-prod
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-prod
spec:
  volumeName: mongo-pv-prod
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo6-deployment-prod
  labels:
    app: mongo-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-prod
  template:
    metadata:
      labels:
        app: mongo-prod
    spec:
      containers:
        - image: mongo:6.0
          name: mongo6
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets-prod
                  key: mongo_user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets-prod
                  key: mongo_password
          volumeMounts:
            - name: mongo-prod
              mountPath: /data/db
      volumes:
        - name: mongo-prod
          persistentVolumeClaim:
            claimName: mongo-pvc-prod
---
apiVersion: v1
kind: Service
metadata:
  name: mongo6-service-prod
spec:
  type: ClusterIP
  selector:
    app: mongo-prod
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
