apiVersion: v1
kind: ConfigMap
metadata:
  name: back-gateway-prod
data:
  auth_server: http://manantial.test/realms/manantial-realm
  customers_url: http://backend-customer-service-prod:8081/v1/customers
  customer_baseurl: http://backend-customer-service-prod:8081

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: back-customer-prod
data:
  db_name: customers_db
  db_host:  mongodb://admin:admin@mongo6-service-prod:27017/customers_db?authSource=admin
  kafka_host: kafka-prod:9092

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: back-consumer-prod
data:
  kafka_host: kafka-prod:9092
  redis_host: redis7-service-prod
  redis_port: "6379"
  storage_type: local
  storage_path: /pdfs
