---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-server
data:
  auth_server: http://keycloak:8080/realms/manantial-realm
  customers_url: http://users-service:8081/v1/customers

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customers-service
data:
  db_name: customers_db
  db_host:  mongodb://mongo6-posts:27017/customers_db
  kafka_host: http://kafka:9092
