apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
type: Opaque
data:
  keycloak_client_id: Y2xpZW50ZV9hdXRob3JpemF0aW9u
---


apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  mongo_user: YWRtaW4=
  mongo_password: YWRtaW4=
