apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-staging
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-staging
spec:
  volumeName: redis-pv-staging
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis7-deployment-staging
  labels:
    app: redis-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-staging
  template:
    metadata:
      labels:
        app: redis-staging
    spec:
      containers:
        - image: redis:7.2
          name: redis7
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-staging
          persistentVolumeClaim:
            claimName: redis-pvc-staging

---
apiVersion: v1
kind: Service
metadata:
  name: redis7-service-staging
spec:
  type: ClusterIP
  selector:
    app: redis-staging
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379





