{
 "title": "Java Metrics",
 "tags": [
  "java",
  "jvm"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Heap Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}"
    }
   ]
  },
  {
   "title": "Threads Live",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "jvm_threads_live_threads" }
   ]
  },
  {
   "title": "GC Time (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[1m])"
    }
   ]
  }
 ]
}